version: '3.8'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - wdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  wdata:
