version: '3.8'

services:
  db:
    image: postgres:15.4
    restart: always
    env_file:
      - .env.production
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5435:5435
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    command: npm run start:prod
    volumes:
      - /etc/letsencrypt/live/war-track.com/privkey.pem:/etc/letsencrypt/live/war-track.com/privkey.pem
      - /etc/letsencrypt/live/war-track.com/fullchain.pem:/etc/letsencrypt/live/war-track.com/fullchain.pem
    ports:
      - 443:443
      - 80:80
    depends_on:
      - db
    env_file:
      - ./.env.production
volumes:
  pgdata:
