# Building stage
FROM node:18-alpine as build_stage
WORKDIR /app
COPY tsconfig*.json ./
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Deploying stage
FROM node:18-alpine as deploying_stage
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build_stage /app/dist ./dist/
EXPOSE 80
CMD ["node", "dist/main.js"]