export enum EquipmentType {
  AllTypes = 'All Types',
  Aircraft = 'Aircraft',
  AntiAircraftGuns = 'Anti-Aircraft Guns',
  ArmouredFightingVehicles = 'Armoured Fighting Vehicles',
  ArmouredPersonnelCarriers = 'Armoured Personnel Carriers',
  ArtillerySupportVehiclesAndEquipment = 'Artillery Support Vehicles And Equipment',
  CommandPostsAndCommunicationsStations = 'Command Posts And Communications Stations',
  EngineeringVehiclesAndEquipment = 'Engineering Vehicles And Equipment',
  Helicopters = 'Helicopters',
  InfantryFightingVehicles = 'Infantry Fighting Vehicles',
  InfantryMobilityVehicles = 'Infantry Mobility Vehicles',
  JammersAndDeceptionSystems = 'Jammers And Deception Systems',
  MineResistantAmbushProtected = 'Mine-Resistant Ambush Protected',
  MultipleRocketLaunchers = 'Multiple Rocket Launchers',
  NavalShipsAndSubmarines = 'Naval Ships and Submarines',
  Radars = 'Radars',
  ReconnaissanceUnmannedAerialVehicles = 'Reconnaissance Unmanned Aerial Vehicles',
  SelfPropelledAntiAircraftGuns = 'Self-Propelled Anti-Aircraft Guns',
  SelfPropelledAntiTankMissileSystems = 'Self-Propelled Anti-Tank Missile Systems',
  SelfPropelledArtillery = 'Self-Propelled Artillery',
  SurfaceToAirMissileSystems = 'Surface-To-Air Missile Systems',
  Tanks = 'Tanks',
  TowedArtillery = 'Towed Artillery',
  TrucksVehiclesAndJeeps = 'Trucks, Vehicles, and Jeeps',
  UnmannedCombatAerialVehicles = 'Unmanned Combat Aerial Vehicles',
}
