on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}

        script: |
          cd /home/war-statistics-api/ && git pull origin main
          docker-compose -f docker-compose.prod.yml --env-file .env.production down
          docker-compose -f docker-compose.prod.yml --env-file .env.production build
          docker image prune -f
          docker-compose -f docker-compose.prod.yml --env-file .env.production up -d
    
    
